services:
  - type: web
    name: bianluns-pocketbase
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: 8090
    healthCheckPath: /api/health
    disk:
      name: pb_data
      mountPath: /pb_data
      sizeGB: 1

